# ndarray 和 原声list 的速度对比 

In [1]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

1.492516040802002 0.16065216064453125


 # numpy的nd array对象

In [6]:
import numpy
list1 = [1,2,3,4]
oneArray = numpy.array(list1)
print(type(oneArray))
print(oneArray)

# np创建数组
    #1
t1 = numpy.array([1,2,3])
print(t1)
print(type(t1))

    #2
t2 = np.array(range(10))
print(t2)

    #3 np里的range
t3 = numpy.arange(0,10,2)
print(t3)


<class 'numpy.ndarray'>
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# 创建二维数组

In [7]:
import numpy
list2 = [[1,2],[3,4],[5,6]]
twoArray = numpy.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


# 常用属性

In [10]:
list2 = [[1,2],[3,4],[5,6]]
twoArray2 = numpy.array(list2)

#ndim 获取维度
print(twoArray2.ndim)

#形状
print(twoArray2.shape)

#有多少个元素
print(twoArray2.size)

2
(3, 2)
6


# 调整数组的形状

In [29]:
three = numpy.array([[1,2,3],[4,5,6]])
# 修改的是原来的数组
three.shape = (3,2)

#返回一个新数组 reshape传递的参数应为一个（a,b）的元组形式
four = three.reshape(3,2)
print(f'four = {four}')


#两种方式变一维数组  这里一定得是6， 才能变成1x6的矩阵，  
# 若是6,1的话 每个元素会变成一个单独的矩阵

# F （Fortran风格） 意味着以列的顺序展开，默认是C 以行展开
five = four.reshape((6,),order = 'F')
six = four.flatten(order = 'F')
print(f'five = {five}')
print(f'six = {six}')
#数组的形状
t = numpy.arange(24)
print(f't = {t}')
print(t.shape)

#将t转换为二维

t1 = t.reshape((4,6))  # 两个括弧
print(f't1 = {t1}')
print(t1.shape)

four = [[1 2]
 [3 4]
 [5 6]]
five = [1 3 5 2 4 6]
six = [1 3 5 2 4 6]
t = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
t1 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


# 所以reshape的一个括号和两个括号都可以作为和法参数

In [33]:
t = numpy.arange(24)
print(f't = {t}')
print(f't.shape = {t.shape}')
t1 = t.reshape((4,6))
t2 = t.reshape(4,6)
print(f't1 = {t1}')
print(f't2 = {t2}')
print(f't1.shape = {t1.shape}')
print(f't2.shape = {t2.shape}')

t = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
t.shape = (24,)
t1 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
t2 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
t1.shape = (4, 6)
t2.shape = (4, 6)


# 将数组转换为list

In [34]:
a = numpy.array([9,12,77,26,38])
list_a = a.tolist()
print(f'list_a = {list_a}')
print(f'type of list_a = {type(list_a)})')

list_a = [9, 12, 77, 26, 38]
type of list_a = <class 'list'>)


# numpy 的数据类型

In [38]:
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = numpy.array([1,2,3,4,5], dtype = numpy.int16)
print(f.itemsize) # 1 np.int8(一个字节)

# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(numpy.int64)
print(f1.dtype)

# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))
arr = numpy.array([random.random() for i in range(10)])

# 取小数点后两位
print(numpy.round(arr,2))

2
int16
int64
0.3
[0.26 0.92 0.02 0.22 0.4  0.94 0.86 0.64 0.36 0.18]


# 数组的计算
numpy的广播机制存在，加减乘除的值被广播到所有元素上
也就是说numpy数组的加减乘除一个常数，结果是数组中的所有元素进行加减乘除这个常数

In [42]:

t1 = numpy.arange(24).reshape(6,4)
print(t1+2)

print('-'*50)
print(t1*2)
print('-'*50)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------------------------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------------------------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# 数组之间的操作
同种形状的数组对应位置进行计算

In [43]:
t1 = numpy.arange(24).reshape(6,4)
t2 = numpy.arange(100,124).reshape(6,4)
print(t1+t2)
print('-'*50)
print(t1*t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


不同形状的多维数组不能计算

In [44]:
t1 = numpy.arange(24).reshape(4,6)
t2 = numpy.arange(18).reshape(3,6)
print(t1-t2)
# ValueError: operands could not be broadcast together with shapes (4,6) (3,6)

ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

行数或者列数相同的一维数组和多维数组可以进行计算：

行形状相同（会与每一行数组的对应位相操作)

In [47]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print(t2)
print('-'*50)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
--------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


列形状相同（会与每一个相同维度的数组的对应位相操作)

In [46]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 轴

In [48]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

[5 7 9]
[ 6 15]
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


# 数组的索引与切片

一维数组的操作方法

In [49]:
import numpy as np
a = np.arange(10)  
print(a[2:7:2])# 冒号分割切片参数 start:stop:step 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [50]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


# 数组中数值的修改

In [51]:
import numpy as np
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
#
# # 修改某一列的值
t[:, 1] = 0
# # 修改连续多行
t[1:3, :] = 0
#
# # 修改连续多列
t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0 # 与
t[(t < 2) | (t > 6)] = 0 # 或
t[~(t > 6)] = 0 # 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]
