# ndarray 和 原声list 的速度对比 

In [1]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

1.492516040802002 0.16065216064453125


 # numpy的nd array对象

In [6]:
import numpy
list1 = [1,2,3,4]
oneArray = numpy.array(list1)
print(type(oneArray))
print(oneArray)

# np创建数组
    #1
t1 = numpy.array([1,2,3])
print(t1)
print(type(t1))

    #2
t2 = np.array(range(10))
print(t2)

    #3 np里的range
t3 = numpy.arange(0,10,2)
print(t3)


<class 'numpy.ndarray'>
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# 创建二维数组

In [7]:
import numpy
list2 = [[1,2],[3,4],[5,6]]
twoArray = numpy.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


# 常用属性

In [10]:
list2 = [[1,2],[3,4],[5,6]]
twoArray2 = numpy.array(list2)

#ndim 获取维度
print(twoArray2.ndim)

#形状
print(twoArray2.shape)

#有多少个元素
print(twoArray2.size)

2
(3, 2)
6


# 调整数组的形状

In [29]:
three = numpy.array([[1,2,3],[4,5,6]])
# 修改的是原来的数组
three.shape = (3,2)

#返回一个新数组 reshape传递的参数应为一个（a,b）的元组形式
four = three.reshape(3,2)
print(f'four = {four}')


#两种方式变一维数组  这里一定得是6， 才能变成1x6的矩阵，  
# 若是6,1的话 每个元素会变成一个单独的矩阵

# F （Fortran风格） 意味着以列的顺序展开，默认是C 以行展开
five = four.reshape((6,),order = 'F')
six = four.flatten(order = 'F')
print(f'five = {five}')
print(f'six = {six}')
#数组的形状
t = numpy.arange(24)
print(f't = {t}')
print(t.shape)

#将t转换为二维

t1 = t.reshape((4,6))  # 两个括弧
print(f't1 = {t1}')
print(t1.shape)

four = [[1 2]
 [3 4]
 [5 6]]
five = [1 3 5 2 4 6]
six = [1 3 5 2 4 6]
t = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
t1 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


# 所以reshape的一个括号和两个括号都可以作为和法参数

In [33]:
t = numpy.arange(24)
print(f't = {t}')
print(f't.shape = {t.shape}')
t1 = t.reshape((4,6))
t2 = t.reshape(4,6)
print(f't1 = {t1}')
print(f't2 = {t2}')
print(f't1.shape = {t1.shape}')
print(f't2.shape = {t2.shape}')

t = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
t.shape = (24,)
t1 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
t2 = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
t1.shape = (4, 6)
t2.shape = (4, 6)


# 将数组转换为list

In [34]:
a = numpy.array([9,12,77,26,38])
list_a = a.tolist()
print(f'list_a = {list_a}')
print(f'type of list_a = {type(list_a)})')

list_a = [9, 12, 77, 26, 38]
type of list_a = <class 'list'>)


# numpy 的数据类型

In [38]:
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = numpy.array([1,2,3,4,5], dtype = numpy.int16)
print(f.itemsize) # 1 np.int8(一个字节)

# 获取数据类型
print(f.dtype)

# 调整数据类型
f1 = f.astype(numpy.int64)
print(f1.dtype)

# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))
arr = numpy.array([random.random() for i in range(10)])

# 取小数点后两位
print(numpy.round(arr,2))

2
int16
int64
0.3
[0.26 0.92 0.02 0.22 0.4  0.94 0.86 0.64 0.36 0.18]


# 数组的计算
numpy的广播机制存在，加减乘除的值被广播到所有元素上
也就是说numpy数组的加减乘除一个常数，结果是数组中的所有元素进行加减乘除这个常数

In [42]:

t1 = numpy.arange(24).reshape(6,4)
print(t1+2)

print('-'*50)
print(t1*2)
print('-'*50)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------------------------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------------------------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# 数组之间的操作
同种形状的数组对应位置进行计算

In [43]:
t1 = numpy.arange(24).reshape(6,4)
t2 = numpy.arange(100,124).reshape(6,4)
print(t1+t2)
print('-'*50)
print(t1*t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


不同形状的多维数组不能计算

In [44]:
t1 = numpy.arange(24).reshape(4,6)
t2 = numpy.arange(18).reshape(3,6)
print(t1-t2)
# ValueError: operands could not be broadcast together with shapes (4,6) (3,6)

ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

行数或者列数相同的一维数组和多维数组可以进行计算：

行形状相同（会与每一行数组的对应位相操作)

In [47]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print(t2)
print('-'*50)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
--------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


列形状相同（会与每一个相同维度的数组的对应位相操作)

In [46]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 轴

In [48]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

[5 7 9]
[ 6 15]
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


# 数组的索引与切片

一维数组的操作方法

In [49]:
import numpy as np
a = np.arange(10)  
print(a[2:7:2])# 冒号分割切片参数 start:stop:step 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

[2 4 6]
2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [50]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


# 数组中数值的修改

In [51]:
import numpy as np
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
#
# # 修改某一列的值
t[:, 1] = 0
# # 修改连续多行
t[1:3, :] = 0
#
# # 修改连续多列
t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0 # 与
t[(t < 2) | (t > 6)] = 0 # 或
t[~(t > 6)] = 0 # 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]


# 数组的添加、删除、去重

append方法

In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('-'*50)

#由于两个ndarray形状不同，所以会转成一行
print(np.append(a,[7,8,9]))
print('-'*50)

#沿着轴0添加元素
print(np.append(a,[[7,8,9]],axis = 0))
print('-'*50)\
    
#沿着轴1添加元素
print(np.append(a,[[5,5,5],[7,8,9]],axis = 1))



[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


insert方法

In [21]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print('-'*50)
print('未传递 Axis 参数。 在插入之前输入数组会被展开。中间的参数3就是插入在展开后的数组下标')
print(np.insert(a, 3, [11, 12]))
print('-'*50)
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 2, [11], axis=0))
print('-'*50)
print('沿轴 1 广播：')
print(np.insert(a, 2, 11, axis=1))

[[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
未传递 Axis 参数。 在插入之前输入数组会被展开。中间的参数3就是插入在展开后的数组下标
[ 1  2  3 11 12  4  5  6]
--------------------------------------------------
传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [ 3  4]
 [11 11]
 [ 5  6]]
--------------------------------------------------
沿轴 1 广播：
[[ 1  2 11]
 [ 3  4 11]
 [ 5  6 11]]


# 数组的删除

In [ ]:
"""
numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
如果未提供轴参数， 则输入数组将展开。
参 数 说 明 ： 
arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组 axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
"""


In [23]:
import numpy as np
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开,然后删除一维数组中的下标位置。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开,然后删除一维数组中的下标位置。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




# 数组去重 

In [ ]:
# numpy.unique 函数用于去除数组中的重复元素。，返回一个新数组
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''

In [29]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')

print ('第一个数组的去重值：')
u = np.unique(a)
print (u)

print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


返回去重元素的重复数量：
[3 2 2 1 1 1]


# numpy的计算

In [47]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result)

# 2# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=1)
print(result)

# 3. 获取最小值
result = np.min(score)
print(result)

# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)
# 5. 数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

# 6. 求平均值
print(score)
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)   

# 7. 求前缀和
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''

print('\n')
# 8. argmin 求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的 81 是第二排的，是从前往后遍历的
print(result,res)
print('\n')
# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)

88
[88 82 81]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]
[[80 88]
 [82 81]
 [75 81]]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


[2 1] [75 81]


[2.94392029 3.29983165]


# 数组的拼接和切割


数组拼接（其中只有stack增加维度，在哪个轴stack，哪个轴的维度就+1）

In [53]:
import numpy as np
# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# 要求 a,b 两个数组的维度相同
print ('沿轴 0 concatenate两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 concatenate两个数组：')
print (np.concatenate((a,b),axis = 1))

# 2. 根据轴进行堆叠
# stack就加了维度了 变成了 2 2 2

print ('沿轴 0 stack两个数组：')
print (np.stack((a,b),axis= 0))
print ('\n')
print ('沿轴 1 stack两个数组：')
print (np.stack((a,b),axis = 1))

# 3. 矩阵垂直拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)
# 4. 矩阵水平拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

沿轴 0 concatenate两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 concatenate两个数组：
[[1 2 5 6]
 [3 4 7 8]]
沿轴 0 stack两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 stack两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


数组分割

In [59]:
import numpy as np

# 1. 将一个数组分割为多个子数组
'''参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置
（左开右闭）
axis：沿着哪个维度进行切向，默认为 0，横向切分。为 1 时，纵向切分
'''
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)

# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
print('\n2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。\n')
harr = np.floor(10*np.random.random((2, 6)))
print ('原 array：')
print(harr)
print ('拆分后：')
print(np.hsplit(harr, 3))

# 3.numpy.vsplit 沿着垂直轴分割
print('\n3.numpy.vsplit 沿着垂直轴分割\n')
a = np.arange(16).reshape(4,4)
print ('第一个数组：')
print (a)
print ('\n')
print ('竖直分割：')
b = np.vsplit(a,2)
print (b)

将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。

原 array：
[[5. 4. 4. 3. 3. 1.]
 [2. 4. 8. 2. 8. 5.]]
拆分后：
[array([[5., 4.],
       [2., 4.]]), array([[4., 3.],
       [8., 2.]]), array([[3., 1.],
       [8., 5.]])]

3.numpy.vsplit 沿着垂直轴分割

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# nan和inf

In [65]:
import numpy as np
# 创建一个 nan 和 inf #
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))
# --判断数组中为 nan 的个数
t = np.arange(24,dtype=float).reshape(4,6)
# 将三行四列的数改成 nan
t[3,4] = np.nan
# 可以使用 np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
# 并 且 np.nan != np.nan 结果 是 TRUE
# 所以我们可以使用这两个结合使用判断 nan 的个数
print(np.count_nonzero(t != t))
# 将 nan 替换为 0
t[np.isnan(t)] = 0 
print(t)
# 将数组中的一部分替换 nan
t[1,3:] = np.nan
print(t)
print('-------------------')
# 遍历每一列，然后判断每一列是否有 nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:,i]
    # 判断当前列的数据中是否含有 nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有 nan
    if nan_num != 0:
    # 将这一列不为 nan 的数据拿出来
        temp_col_not_nan = temp_col[temp_col == temp_col]
    # 将 nan 替换成这一列的平均值
        temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )
print(t)

nan <class 'float'>
inf <class 'float'>
23
1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]
-------------------
[[ 0.          1.          2.          3.          4.          5.        ]
 [ 6.          7.          8.         13.          6.66666667 15.        ]
 [12.         13.         14.         15.         16.         17.        ]
 [18.         19.         20.         21.          0.         23.        ]]


# 二维数组的转置、轴滚动

In [66]:
#对换数组的维度
import numpy as np
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a )
print ('\n')
print ('对换数组：')
print (np.transpose(a))



原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [67]:
# 与 transpose 一致
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a)
print ('\n')
print ('转置数组：')
print (a.T)
# 函数用于交换数组的两个轴
#这个swapaxis在二维数组中与transpose没啥区别，但在多维数组中就明显了

t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)
print (' 原 数 组 ：')
print (t1)
print ('\n')
print ('调用 swapaxes 函数后的数组：')
print (re)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


### np.rollaxis()方法 将数组的第一参数维度滚动到第二参数维度之前，注意是之前

In [100]:
t = np.array([ [[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]] ])
print('原数组')
print(t)
print('\n')
print(t.shape)
t=np.rollaxis(t,0,3)
print(t.shape)
print(t)

原数组
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


(3, 2, 2)
(2, 2, 3)
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]
